// Command gendocs renders the published error contract from the Go source of
// truth (CONVENTIONS §7.1), so the documentation cannot disagree with the
// server's behaviour.
//
// It writes two artifacts from the SAME table, `errs.Catalogue()`:
//
//   - docs/api/errors.md — the human-readable catalogue.
//   - docs/api/openapi.errors.yaml — an OpenAPI fragment carrying the
//     `chronos.errors.v1.ErrorDetail` schema with `reason` as a closed enum. It
//     is fed to protoc-gen-connect-openapi as `override=`, so the REST reference
//     publishes the exact set of reasons a client may switch on.
//
// The second artifact exists because a reason code that appears only in prose is
// a reason code every client hardcodes from a string it scraped out of a live
// response. Generating both from one table is what makes them agree; a test in
// internal/platform/errs already fails if a declared Reason is missing from the
// table, so neither can silently fall behind the server.
//
// It MUST run before `buf generate --template buf.gen.openapi.yaml`, which
// consumes the fragment.
package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/chronos/chronos-go/internal/platform/errs"
)

func main() {
	writeCatalogue()
	writeOpenAPIErrors()
}

func writeCatalogue() {
	var b strings.Builder
	b.WriteString("# API Error Catalogue\n\n")
	b.WriteString("> **Generated** from `internal/platform/errs`. Do not edit.\n")
	b.WriteString("> Run `make api-docs`.\n\n")
	b.WriteString("Clients branch on `reason`, never on the HTTP status or the message.\n")
	b.WriteString("The status and Connect code are shown for transport handling only.\n\n")
	b.WriteString("| Reason | Connect code | HTTP | Retryable | Meaning | Client should |\n")
	b.WriteString("| --- | --- | --- | --- | --- | --- |\n")
	for _, d := range errs.Catalogue() {
		retry := "no"
		if d.Retryable {
			retry = "**yes**"
		}
		fmt.Fprintf(&b, "| `%s` | `%s` | %d | %s | %s | %s |\n",
			d.Reason, d.ConnectCode, d.HTTPStatus, retry, d.Meaning, d.ClientShould)
	}
	b.WriteString(`
## The distinction that matters most

` + "`ACCESS_DENIED`" + ` and ` + "`PLAN_UPGRADE_REQUIRED`" + ` are both refusals and must never
be collapsed into a generic 403. One means *ask an admin*; the other means
*upgrade your plan*. They lead to completely different user journeys, and a
client that cannot tell them apart will send people down the wrong one.

## Why NOT_FOUND is deliberately ambiguous

` + "`NOT_FOUND`" + ` covers three cases: the resource does not exist, it exists but the
caller may not know that, and it exists but the caller is refused. This is
intentional (ADR-036) — distinguishing them across a tenant boundary would let
identifiers be probed for existence.

Inside a tenant, where the caller has already proven membership, errors *are*
specific.
`)
	const out = "docs/api/errors.md"
	// #nosec G306 -- generated documentation is intended to be world-readable
	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "gendocs:", err)
		os.Exit(1)
	}
	fmt.Printf("  wrote %s (%d reasons)\n", out, len(errs.Catalogue()))
}

// writeOpenAPIErrors emits the OpenAPI fragment the REST reference merges in.
//
// It carries `chronos.errors.v1.ErrorDetail` — the message that actually travels
// in a Connect error's `details` array — with `reason` rendered as a CLOSED enum
// of the catalogue's reasons. protoc-gen-connect-openapi does not emit this
// schema on its own: `trim-unused-types` drops it, correctly, because no
// operation's request or response references it. It reaches a client only
// through an error, which the generator models as an untyped `Any`.
//
// The per-reason meaning and client action ride along in the description, so the
// two published artifacts say the same thing in the two places a client actually
// looks.
func writeOpenAPIErrors() {
	var b strings.Builder
	b.WriteString("# GENERATED by internal/tools/gendocs from internal/platform/errs.\n")
	b.WriteString("# Do not edit. Run `make api-docs`.\n")
	b.WriteString("#\n")
	b.WriteString("# Merged into docs/api/chronos-openapi.yaml as the generator's `override=`\n")
	b.WriteString("# input, which replaces components by key.\n")
	b.WriteString("openapi: 3.1.0\n")
	b.WriteString("info:\n  title: Chronos error contract\n  version: v1\n")
	b.WriteString("components:\n  schemas:\n")

	b.WriteString("    chronos.errors.v1.ErrorDetail:\n")
	b.WriteString("      type: object\n")
	b.WriteString("      title: Error detail\n")
	b.WriteString("      description: |\n")
	b.WriteString("        The machine-readable part of a failed response. It travels inside the\n")
	b.WriteString("        Connect error's `details` array, alongside the transport `code`.\n\n")
	b.WriteString("        Branch on `reason`. NEVER on the HTTP status and never on `message`:\n")
	b.WriteString("        one status covers several reasons that lead to completely different\n")
	b.WriteString("        user journeys, and messages are prose that changes without notice.\n\n")
	b.WriteString("        | Reason | Connect code | HTTP | Retryable | The client should |\n")
	b.WriteString("        | --- | --- | --- | --- | --- |\n")
	for _, d := range errs.Catalogue() {
		retry := "no"
		if d.Retryable {
			retry = "**yes**"
		}
		fmt.Fprintf(&b, "        | `%s` | `%s` | %d | %s | %s |\n",
			d.Reason, d.ConnectCode, d.HTTPStatus, retry, d.ClientShould)
	}
	b.WriteString("      properties:\n")
	b.WriteString("        reason:\n          type: string\n")
	b.WriteString("          description: |\n")
	b.WriteString("            The stable reason. This enum is the complete set the server can\n")
	b.WriteString("            return; it is generated from the server's own table, so a value\n")
	b.WriteString("            outside it means the client is older than the server.\n")
	b.WriteString("          enum:\n")
	for _, d := range errs.Catalogue() {
		fmt.Fprintf(&b, "            - %s\n", d.Reason)
	}
	b.WriteString("          examples:\n            - ACCESS_DENIED\n")
	b.WriteString("        metadata:\n          type: object\n")
	// Bounded, like every other value in the published document (see
	// internal/tools/checkopenapi/bounds.go). A metadata value is a short label —
	// a field name, a limit, a plan — and the ceiling says so; the pattern says it
	// is one line, which is what "never SQL, never driver text" means in a keyword
	// rather than in prose.
	b.WriteString("          additionalProperties:\n            type: string\n")
	b.WriteString("            maxLength: 1024\n")
	// Single-quoted in YAML deliberately: a double-quoted scalar processes `\r`
	// and `\n` as escapes, which would put a real carriage return inside the
	// regex instead of the two-character escape the regex needs.
	b.WriteString("            pattern: '^[^\\r\\n]*$'\n")
	b.WriteString("          maxProperties: 32\n")
	b.WriteString("          description: |\n")
	b.WriteString("            Client-safe structured detail: the limit that was exceeded, the\n")
	b.WriteString("            field that failed validation, the plan that would satisfy the\n")
	b.WriteString("            request. Never personal data, never SQL, never driver text.\n")
	b.WriteString("          examples:\n            - {field: email}\n")
	b.WriteString("        traceId:\n          type: string\n")
	// A W3C Trace Context trace id: 32 lowercase hex characters. The empty
	// alternative is the case where the request carried no trace — the field is
	// present and blank rather than absent, because this document publishes
	// default values (see info.description).
	b.WriteString("          maxLength: 32\n")
	b.WriteString("          pattern: '^$|^[0-9a-f]{32}$'\n")
	b.WriteString("          description: |\n")
	b.WriteString("            Correlation id for this request. The server-side cause is NOT in\n")
	b.WriteString("            this message; an operator finds it by searching traces for this\n")
	b.WriteString("            id, so a user can paste it into a support ticket and lose nothing.\n")
	b.WriteString("          examples:\n            - 4bf92f3577b34da6a3ce929d0e0e4736\n")
	b.WriteString("      required:\n        - reason\n")

	// The envelope, overridden by key so the generated one is replaced.
	//
	// protoc-gen-connect-openapi synthesises `connect.error_details.Any` from the
	// PROTOCOL, which cannot know what this server puts inside it, so it published
	// the only thing it could: a `oneOf` holding one free-form object, with a
	// `discriminator: {propertyName: type}` whose target declares no `type`
	// property. That is an invalid discriminator, and it described a payload no
	// client could decode.
	//
	// This server attaches exactly ONE detail type, and it does so at exactly one
	// place — internal/server/connect/errors.go builds every wire error, and every
	// error in this system passes through it. So the envelope's contents are known
	// here, and naming them turns `debug` from "some object" into the message a
	// client is about to branch on.
	//
	// Written in the hoisted `allOf` form the fixer would produce anyway, so the
	// two agree and `make api-docs` stays idempotent.
	b.WriteString("    connect.error_details.Any:\n")
	b.WriteString("      type: object\n")
	b.WriteString("      title: Error detail envelope\n")
	b.WriteString("      description: |\n")
	b.WriteString("        One entry of a Connect error's `details` array.\n\n")
	b.WriteString("        This server attaches exactly one detail type — the `ErrorDetail` below —\n")
	b.WriteString("        and attaches it to every error it raises, so `debug` is the decoded form\n")
	b.WriteString("        of `value` rather than an arbitrary message. Read `debug.reason`.\n")
	b.WriteString("      properties:\n")
	b.WriteString("        type:\n          type: string\n")
	b.WriteString("          maxLength: 512\n")
	b.WriteString("          pattern: '^[A-Za-z0-9.-]+/[A-Za-z0-9_.]+$'\n")
	b.WriteString("          examples:\n            - type.googleapis.com/chronos.errors.v1.ErrorDetail\n")
	b.WriteString("          description: |\n")
	b.WriteString("            The detail's type URL. Today it is always\n")
	b.WriteString("            `type.googleapis.com/chronos.errors.v1.ErrorDetail`; it is published as\n")
	b.WriteString("            a pattern rather than a constant so that adding a second detail type\n")
	b.WriteString("            is not a breaking change to this document.\n")
	b.WriteString("        value:\n          type: string\n")
	b.WriteString("          contentEncoding: base64\n")
	b.WriteString("          maxLength: 65536\n")
	b.WriteString("          pattern: '^[A-Za-z0-9+/]*={0,2}$'\n")
	b.WriteString("          description: |\n")
	b.WriteString("            The detail, protobuf-serialized and base64-encoded. A client that reads\n")
	b.WriteString("            `debug` never needs this.\n")
	b.WriteString("        debug:\n")
	b.WriteString("          allOf:\n            - $ref: '#/components/schemas/chronos.errors.v1.ErrorDetail'\n")
	b.WriteString("          title: Debug\n")
	b.WriteString("          description: |\n")
	b.WriteString("            The decoded detail. Branch on its `reason`.\n")

	const out = "docs/api/openapi.errors.yaml"
	// #nosec G306 -- generated documentation is intended to be world-readable
	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "gendocs:", err)
		os.Exit(1)
	}
	fmt.Printf("  wrote %s (%d reasons as an enum)\n", out, len(errs.Catalogue()))
}
