// Command apidocs serves the API contract: the REST/OpenAPI surface, the gRPC
// descriptor set, the proto sources and the error catalogue.
//
// Everything is embedded, so the binary is self-contained and the image needs
// no volume. Assets are generated — `make api-docs` regenerates and copies
// them here — so the documentation cannot drift from the schema the server
// actually serves (CONVENTIONS §7.1).
package main

import (
	"context"
	"embed"
	"errors"
	"flag"
	"fmt"
	"io/fs"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"
)

//go:embed assets
var assets embed.FS

func main() {
	addr := flag.String("addr", envOr("DOCS_ADDR", ":"+envOr("DOCS_PORT", "8091")), "listen address")
	flag.Parse()

	// Used only in the copy-pasteable examples on the index page.
	apiPort := envOr("API_PORT", "8090")
	docsPort := strings.TrimPrefix(*addr, ":")

	log := slog.New(slog.NewTextHandler(os.Stdout, &slog.HandlerOptions{Level: slog.LevelInfo}))

	sub, err := fs.Sub(assets, "assets")
	if err != nil {
		log.Error("embedded assets unavailable", "error", err)
		os.Exit(1)
	}

	mux := http.NewServeMux()
	mux.HandleFunc("GET /{$}", page(indexHTML(apiPort, docsPort)))
	mux.HandleFunc("GET /reference", page(referenceHTML()))
	// The gRPC counterpart to /reference, generated by protoc-gen-doc and given
	// the shared nav so readers can move between surfaces. Done once at startup.
	grpcDoc, err := fs.ReadFile(sub, "grpc.html")
	if err != nil {
		log.Error("gRPC reference missing — run `make api-docs`", "error", err)
		os.Exit(1)
	}
	grpcDoc = injectNav(grpcDoc, "grpc")
	mux.HandleFunc("GET /grpc", func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		_, _ = w.Write(grpcDoc)
	})
	mux.HandleFunc("GET /healthz", func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte("ok"))
	})
	// Serve the generated artifacts directly: spec, descriptor set, catalogue,
	// and the proto sources under /proto/.
	mux.Handle("GET /", withContentTypes(http.FileServer(http.FS(sub))))

	srv := &http.Server{
		Addr:              *addr,
		Handler:           mux,
		ReadHeaderTimeout: 10 * time.Second,
	}

	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	go func() {
		log.Info("serving api documentation", "addr", *addr)
		if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			log.Error("listen failed", "error", err)
			os.Exit(1)
		}
	}()

	<-ctx.Done()
	shutdownCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	_ = srv.Shutdown(shutdownCtx)
	log.Info("stopped")
}

func page(html string) http.HandlerFunc {
	return func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		_, _ = fmt.Fprint(w, html)
	}
}

// withContentTypes labels artifacts that Go's sniffer gets wrong, so a browser
// renders YAML and Markdown instead of downloading them.
func withContentTypes(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch {
		case hasSuffix(r.URL.Path, ".yaml"), hasSuffix(r.URL.Path, ".yml"):
			w.Header().Set("Content-Type", "text/yaml; charset=utf-8")
		case hasSuffix(r.URL.Path, ".md"):
			w.Header().Set("Content-Type", "text/markdown; charset=utf-8")
		case hasSuffix(r.URL.Path, ".proto"):
			w.Header().Set("Content-Type", "text/plain; charset=utf-8")
		case hasSuffix(r.URL.Path, ".binpb"):
			w.Header().Set("Content-Type", "application/octet-stream")
		case hasSuffix(r.URL.Path, ".js"):
			w.Header().Set("Content-Type", "text/javascript; charset=utf-8")
			w.Header().Set("Cache-Control", "public, max-age=86400")
		}
		next.ServeHTTP(w, r)
	})
}

func hasSuffix(s, suf string) bool {
	return len(s) >= len(suf) && s[len(s)-len(suf):] == suf
}

func envOr(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}
