package main

import (
	"bytes"
	"fmt"
)

// The documentation site is deliberately two first-class surfaces, not one with
// an appendix: REST consumers and gRPC consumers are different audiences and
// neither should feel like an afterthought.
//
// Both are generated from the same protos, so they cannot disagree.

const navHTML = `<nav class="chrono-nav">
  <a class="brand" href="/">Chronos API</a>
  <a href="/reference"%s>REST</a>
  <a href="/grpc"%s>gRPC</a>
  <a href="/errors.md">Errors</a>
  <a href="/proto/">Protos</a>
</nav>`

const navCSS = `
.chrono-nav{position:sticky;top:0;z-index:9999;display:flex;gap:.25rem;align-items:center;
  padding:.55rem 1rem;background:#111827;color:#e5e7eb;font:14px/1 system-ui,sans-serif;
  border-bottom:1px solid #374151}
.chrono-nav a{color:#9ca3af;text-decoration:none;padding:.4rem .7rem;border-radius:.35rem}
.chrono-nav a:hover{color:#fff;background:#1f2937}
.chrono-nav a[aria-current]{color:#fff;background:#2563eb}
.chrono-nav .brand{font-weight:600;color:#fff;margin-right:.75rem;padding-left:0}
`

// nav renders the shared header, marking the active surface.
func nav(active string) string {
	mark := func(name string) string {
		if name == active {
			return ` aria-current="page"`
		}
		return ""
	}
	return fmt.Sprintf(navHTML, mark("reference"), mark("grpc"))
}

// injectNav splices the shared header into HTML generated by protoc-gen-doc, so
// a reader can move between the gRPC and REST references without going back to
// the index. Rewriting generated output is preferable to forking the template.
func injectNav(doc []byte, active string) []byte {
	head := []byte("<style>" + navCSS + "</style>")
	if i := bytes.Index(doc, []byte("</head>")); i >= 0 {
		doc = append(doc[:i], append(head, doc[i:]...)...)
	}
	if i := bytes.Index(doc, []byte("<body")); i >= 0 {
		if j := bytes.IndexByte(doc[i:], '>'); j >= 0 {
			at := i + j + 1
			doc = append(doc[:at], append([]byte(nav(active)), doc[at:]...)...)
		}
	}
	return doc
}

func indexHTML(apiPort, docsPort string) string {
	return `<!doctype html>
<meta charset="utf-8">
<title>Chronos API</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>
 :root{color-scheme:light dark}
 *{box-sizing:border-box}
 body{margin:0;font:16px/1.65 system-ui,sans-serif}
 ` + navCSS + `
 main{max-width:62rem;margin:0 auto;padding:2.5rem 1.5rem 5rem}
 h1{margin:0 0 .2rem;font-size:1.9rem}
 .sub{opacity:.7;margin:0 0 2.5rem}
 .grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(21rem,1fr));gap:1.25rem}
 .card{border:1px solid color-mix(in srgb,currentColor 18%,transparent);
   border-radius:.7rem;padding:1.25rem 1.35rem}
 .card h2{margin:0 0 .1rem;font-size:1.15rem}
 .card .tag{font-size:.72rem;letter-spacing:.08em;text-transform:uppercase;opacity:.55}
 .card p{margin:.6rem 0 1rem;opacity:.85;font-size:.95rem}
 .btn{display:inline-block;padding:.45rem .9rem;border-radius:.4rem;background:#2563eb;
   color:#fff;text-decoration:none;font-size:.9rem;font-weight:500}
 .btn.ghost{background:transparent;color:inherit;
   border:1px solid color-mix(in srgb,currentColor 30%,transparent)}
 ul{padding-left:1.1rem;margin:.5rem 0} li{margin:.3rem 0;font-size:.93rem}
 a{color:inherit}
 pre{background:color-mix(in srgb,currentColor 7%,transparent);padding:.8rem 1rem;
   border-radius:.45rem;overflow-x:auto;font-size:.83rem;margin:.6rem 0 0}
 code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}
 .note{margin-top:2.5rem;padding:1rem 1.25rem;border-left:3px solid #2563eb;
   background:color-mix(in srgb,#2563eb 8%,transparent);border-radius:0 .4rem .4rem 0;font-size:.93rem}
</style>
` + nav("") + `
<main>
  <h1>Chronos API</h1>
  <p class="sub">One schema. Three protocols on one port — gRPC, gRPC-Web and HTTP/JSON.</p>

  <div class="grid">
    <div class="card">
      <div class="tag">HTTP / JSON</div>
      <h2>REST reference</h2>
      <p>Browse every endpoint and call it from the page. Generated from the
         OpenAPI 3.1 spec.</p>
      <a class="btn" href="/reference">Open REST reference</a>
      <a class="btn ghost" href="/openapi.yaml">openapi.yaml</a>
      <pre><code>curl -X POST http://localhost:` + apiPort + `/chronos.system.v1.SystemService/GetStatus \
  -H 'Content-Type: application/json' -d '{}'</code></pre>
    </div>

    <div class="card">
      <div class="tag">gRPC</div>
      <h2>Service reference</h2>
      <p>Every service, method, message and enum, with the same doc comments the
         schema carries.</p>
      <a class="btn" href="/grpc">Open gRPC reference</a>
      <a class="btn ghost" href="/descriptor.binpb">descriptor.binpb</a>
      <pre><code>grpcurl -protoset descriptor.binpb -plaintext \
  localhost:` + apiPort + ` chronos.system.v1.SystemService/GetStatus</code></pre>
    </div>
  </div>

  <div class="grid" style="margin-top:1.25rem">
    <div class="card">
      <div class="tag">Contract</div>
      <h2>Errors</h2>
      <p>Clients branch on <code>reason</code>, never on the HTTP status or the
         message.</p>
      <ul>
        <li><code>ACCESS_DENIED</code> → ask an admin</li>
        <li><code>PLAN_UPGRADE_REQUIRED</code> → offer an upgrade</li>
      </ul>
      <a class="btn ghost" href="/errors.md">Full catalogue</a>
    </div>

    <div class="card">
      <div class="tag">Code generation</div>
      <h2>Build a client</h2>
      <p>Generate a typed client in any language from the schema itself.</p>
      <ul>
        <li><a href="/proto/">Proto sources</a> — for <code>buf</code> or <code>protoc</code></li>
        <li><a href="/descriptor.binpb">Descriptor set</a> — no reflection needed</li>
      </ul>
      <pre><code>curl -O http://localhost:` + docsPort + `/descriptor.binpb</code></pre>
    </div>
  </div>

  <div class="note">
    <strong>Same schema, both surfaces.</strong> The REST and gRPC references are
    generated from the identical <code>.proto</code> files this server runs, so
    they cannot drift apart. Doc comments are enforced by <code>buf lint</code>
    and breaking changes fail the build.
  </div>
</main>
`
}

// referenceHTML renders the OpenAPI spec with Scalar from an embedded bundle.
//
// No CDN: the binary must work on an air-gapped host, and documentation that
// silently degrades when a third party is unreachable is worse than none.
// Refresh with `make vendor-refresh`.
//
// Scalar over Redoc/Swagger UI: native OpenAPI 3.1 (what we emit) and a built-in
// request console, which matters because our HTTP surface is RPC-shaped POSTs
// that are awkward to hand-craft. It costs ~3x Redoc's bundle — irrelevant for
// an embedded internal tool.
func referenceHTML() string {
	return `<!doctype html>
<meta charset="utf-8">
<title>Chronos API — REST reference</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>body{margin:0}` + navCSS + `</style>
` + nav("reference") + `
<script id="api-reference" data-url="/openapi.yaml"></script>
<script src="/vendor/scalar.js"></script>
`
}
