package main

import (
	"bytes"
	"io"
	"os"
	"path/filepath"
	"testing"
)

// committed is the provisioning directory Grafana actually reads, relative to
// this package.
const committed = "../../../" + defaultOut

// TestGeneratedMatchesCommitted is the whole contract of this tool.
//
// The dashboards under infra/grafana/dashboards are committed AND generated. If
// the two can disagree, the committed copy is what Grafana serves and the
// generator is decoration — which is exactly the state `allowUiUpdates: false`
// exists to prevent from the other direction.
//
// Byte equality rather than JSON equality, deliberately: a semantic comparison
// would pass while a reordering rewrote all seven files on every `make
// dashboards`, and a diff nobody can read is a diff nobody reviews.
func TestGeneratedMatchesCommitted(t *testing.T) {
	dir := t.TempDir()
	if err := run(io.Discard, dir); err != nil {
		t.Fatalf("run() = %v", err)
	}

	for _, g := range dashboards() {
		t.Run(g.name, func(t *testing.T) {
			want := mustRead(t, filepath.Join(committed, g.name))
			got := mustRead(t, filepath.Join(dir, g.name))
			if !bytes.Equal(got, want) {
				t.Errorf("%s differs from the committed copy (%d generated bytes vs %d committed); "+
					"run `make dashboards` and commit the result, or fix the generator",
					g.name, len(got), len(want))
				reportFirstDifference(t, got, want)
			}
		})
	}
}

// TestGenerationIsDeterministic guards the package state the panel constructors
// carry.
//
// The layout cursor and the refId counter are package variables. A dashboard
// function that forgot to reset them, or a future one appended in the wrong
// place, would produce output that depends on what ran before it — and the
// symptom would be a spurious diff on an unrelated file rather than an error.
func TestGenerationIsDeterministic(t *testing.T) {
	first, second := t.TempDir(), t.TempDir()
	if err := run(io.Discard, first); err != nil {
		t.Fatalf("first run: %v", err)
	}
	if err := run(io.Discard, second); err != nil {
		t.Fatalf("second run: %v", err)
	}
	for _, g := range dashboards() {
		a := mustRead(t, filepath.Join(first, g.name))
		b := mustRead(t, filepath.Join(second, g.name))
		if !bytes.Equal(a, b) {
			t.Errorf("%s: two runs in one process produced different bytes; "+
				"a generator function is leaking layout or refId state", g.name)
		}
	}
}

// TestEveryDashboardHasPanels catches the shape of failure a byte comparison
// cannot describe: a dashboard that generates successfully and is empty.
func TestEveryDashboardHasPanels(t *testing.T) {
	for _, g := range dashboards() {
		t.Run(g.name, func(t *testing.T) {
			targetN = 0
			if n := panelCount(g.build()); n == 0 {
				t.Error("generated no panels; an empty dashboard provisions cleanly and shows nothing")
			}
		})
	}
}

// TestPanelQueriesAreNonEmpty asserts every target carries an expression.
//
// A panel with an empty `expr` renders as "No data", which is visually identical
// to a healthy-but-idle panel and to a panel whose metric name is wrong.
func TestPanelQueriesAreNonEmpty(t *testing.T) {
	for _, g := range dashboards() {
		t.Run(g.name, func(t *testing.T) {
			targetN = 0
			panels, _ := lookup(g.build(), "panels").(arr)
			for _, p := range panels {
				po, ok := p.(obj)
				if !ok || lookup(po, "type") == "row" {
					continue
				}
				targets, _ := lookup(po, "targets").(arr)
				if len(targets) == 0 {
					t.Errorf("panel %v has no targets", lookup(po, "title"))
					continue
				}
				for _, tgt := range targets {
					to, _ := tgt.(obj)
					if expr, _ := lookup(to, "expr").(string); expr == "" {
						t.Errorf("panel %v has a target with no expr", lookup(po, "title"))
					}
				}
			}
		})
	}
}

// reportFirstDifference points at the byte that diverged, so a failure names a
// line instead of dumping forty kilobytes of JSON.
func reportFirstDifference(t *testing.T, got, want []byte) {
	t.Helper()
	n := min(len(got), len(want))
	for i := range n {
		if got[i] != want[i] {
			line := 1 + bytes.Count(want[:i], []byte("\n"))
			t.Errorf("first difference at byte %d (line %d):\n  generated: %q\n  committed: %q",
				i, line, excerpt(got, i), excerpt(want, i))
			return
		}
	}
	t.Errorf("one file is a prefix of the other: generated %d bytes, committed %d", len(got), len(want))
}

func excerpt(b []byte, at int) string {
	start := max(at-40, 0)
	end := min(at+40, len(b))
	return string(b[start:end])
}

// mustRead reads a generated or committed dashboard.
func mustRead(t *testing.T, path string) []byte {
	t.Helper()
	// #nosec G304 -- the paths are t.TempDir() and this repository's own
	// provisioning directory; there is no external input.
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading %s: %v", path, err)
	}
	return b
}
