#!/usr/bin/env bash
# SQL belongs in db/query/**.sql, generated by sqlc (ADR-011, CONVENTIONS §8).
#
# The exception is narrow and deliberate: the kernel's postgres adapter uses
# database PRIMITIVES — session settings, advisory locks, role inspection — that
# are not queries against our schema. sqlc has nothing to validate them against,
# so expressing them as .sql files would add ceremony without adding
# verification. They live in internal/adapter/postgres and are reviewed as part
# of the kernel.
#
# Everything else that names a table is a query, and a query belongs in a .sql
# file where sqlc checks it against the real schema.
set -uo pipefail
cd "$(dirname "$0")/.."

G="\033[32m"; R="\033[31m"; X="\033[0m"

# Files permitted to contain SQL primitives.
CARVE_OUT='internal/adapter/postgres/(tx|batch|lease|postgres)\.go'

offenders=$(grep -rnE '(SELECT [a-z_*]|INSERT INTO|UPDATE [a-z_]+ SET|DELETE FROM|TRUNCATE TABLE)' \
    --include='*.go' internal/ cmd/ 2>/dev/null \
  | grep -vE '/gen/sqlc/' \
  | grep -vE "$CARVE_OUT" \
  | grep -vE '^\S+:[0-9]+:\s*(//|\*|/\*)' \
  | grep -vE '_test\.go')

if [ -n "$offenders" ]; then
  echo -e "${R}SQL found in Go source outside the kernel carve-out:${X}"
  echo "$offenders"
  echo
  echo "Move it to db/query/<module>/*.sql and run: make sqlc"
  echo "Then reference the generated exported constant, or the generated method."
  exit 1
fi

echo -e "  ${G}OK${X}    no SQL in Go source outside the kernel carve-out"
