package openfga

import (
	"context"
	"fmt"

	"google.golang.org/grpc"

	fgav1 "github.com/chronos/chronos-go/gen/thirdparty/openfga/v1"
	"github.com/chronos/chronos-go/internal/platform/authz/model"
)

// Deployer writes authorization models and provisions stores.
//
// Separate from Writer and Checker for the same reason those are separate from
// each other: a deploy is an operator action, and nothing in the request path
// should be holding a handle that can replace the model every check pins.
type Deployer struct {
	client fgav1.OpenFGAServiceClient
}

func NewDeployer(conn *grpc.ClientConn) (*Deployer, error) {
	if conn == nil {
		return nil, fmt.Errorf("openfga: a connection is required")
	}
	return &Deployer{client: fgav1.NewOpenFGAServiceClient(conn)}, nil
}

// EnsureStore returns the id of the store named name, creating it if absent.
//
// Idempotent by NAME, because a store id is generated by the server and there is
// nothing else stable to key on. Creating a second store rather than finding the
// first is not a duplicate in the harmless sense: tuples live in a store, so the
// server would answer every check against an empty graph while looking healthy.
func (d *Deployer) EnsureStore(ctx context.Context, name string) (string, error) {
	if name == "" {
		return "", fmt.Errorf("openfga: a store name is required")
	}

	var token string
	for {
		page, err := d.client.ListStores(ctx, &fgav1.ListStoresRequest{ContinuationToken: token})
		if err != nil {
			return "", fmt.Errorf("openfga: listing stores: %w", err)
		}
		for _, s := range page.GetStores() {
			if s.GetName() == name {
				return s.GetId(), nil
			}
		}
		token = page.GetContinuationToken()
		if token == "" {
			break
		}
	}

	created, err := d.client.CreateStore(ctx, &fgav1.CreateStoreRequest{Name: name})
	if err != nil {
		return "", fmt.Errorf("openfga: creating store %q: %w", name, err)
	}
	return created.GetId(), nil
}

// Deploy writes m to the store and returns the immutable model id it was given.
//
// Every deploy produces a NEW model id — OpenFGA does not update models, it
// appends them — and that id is what checks pin (access.md §10). The caller is
// responsible for getting it into configuration before deploying code that
// depends on the new types, which is the ordering that is not negotiable:
//
//  1. deploy the model      (additive only)
//  2. deploy code pinning the new id
//  3. deploy code writing the new tuples
//
// Reversing 1 and 3 means the access projector starts rejecting writes and falls
// behind, which surfaces as newly created resources being unreachable.
func (d *Deployer) Deploy(ctx context.Context, storeID string, m model.Model) (string, error) {
	if storeID == "" {
		return "", fmt.Errorf("openfga: a store id is required to deploy a model")
	}
	types, err := TypeDefinitions(m)
	if err != nil {
		return "", err
	}
	res, err := d.client.WriteAuthorizationModel(ctx, &fgav1.WriteAuthorizationModelRequest{
		StoreId:         storeID,
		SchemaVersion:   schemaVersion,
		TypeDefinitions: types,
	})
	if err != nil {
		return "", fmt.Errorf("openfga: writing the authorization model: %w", err)
	}
	return res.GetAuthorizationModelId(), nil
}

// schemaVersion is OpenFGA's model schema, not ours. 1.1 is what supports typed
// relations — `DirectlyRelatedUserTypes` — and without it a relation cannot say
// WHO may hold it, which is most of what the fragments express.
const schemaVersion = "1.1"

// TypeDefinitions translates the assembled model into OpenFGA's wire form.
//
// This is the only place in the codebase that knows how a fragment becomes a
// Userset. Keeping it here rather than in the model package is what lets a
// module declare a fragment without importing `gen/` — which the domain is
// forbidden from doing (ADR-007), and which is why the fragment vocabulary
// exists at all.
func TypeDefinitions(m model.Model) ([]*fgav1.TypeDefinition, error) {
	if len(m.Types) == 0 {
		return nil, fmt.Errorf("openfga: the model defines no types; every check would be " +
			"evaluated against nothing")
	}

	out := make([]*fgav1.TypeDefinition, 0, len(m.Types))
	for _, t := range m.Types {
		def := &fgav1.TypeDefinition{Type: t.Name}
		if len(t.Relations) == 0 {
			// A type with no relations is legal and meaningful: `user` is the
			// subject of grants and the object of none.
			out = append(out, def)
			continue
		}

		def.Relations = make(map[string]*fgav1.Userset, len(t.Relations))
		def.Metadata = &fgav1.Metadata{
			Relations: make(map[string]*fgav1.RelationMetadata, len(t.Relations)),
		}

		for _, r := range t.Relations {
			userset, err := usersetFor(t.Name, r)
			if err != nil {
				return nil, err
			}
			def.Relations[r.Name] = userset

			refs := make([]*fgav1.RelationReference, 0, len(r.Direct))
			for _, ref := range r.Direct {
				refs = append(refs, relationReference(ref))
			}
			// Metadata is required for EVERY relation, not only the directly
			// assignable ones: OpenFGA validates that a relation named in the
			// model has an entry, and a computed relation simply has an empty
			// list of directly related types.
			def.Metadata.Relations[r.Name] = &fgav1.RelationMetadata{
				DirectlyRelatedUserTypes: refs,
			}
		}
		out = append(out, def)
	}
	return out, nil
}

func relationReference(ref model.TypeRef) *fgav1.RelationReference {
	out := &fgav1.RelationReference{Type: ref.Type}
	switch {
	case ref.Wildcard:
		out.RelationOrWildcard = &fgav1.RelationReference_Wildcard{Wildcard: &fgav1.Wildcard{}}
	case ref.Relation != "":
		out.RelationOrWildcard = &fgav1.RelationReference_Relation{Relation: ref.Relation}
	}
	return out
}

// usersetFor builds the union a relation resolves to.
//
// A single-term relation is emitted as that term rather than as a one-element
// union. Both are accepted, but OpenFGA normalises the model it stores, and a
// gratuitous union makes the deployed model differ from the one we sent for no
// reason — which is noise in exactly the diff an operator reads before the
// highest-blast-radius deploy in the system.
func usersetFor(typeName string, r model.Relation) (*fgav1.Userset, error) {
	var terms []*fgav1.Userset

	if len(r.Direct) > 0 {
		terms = append(terms, &fgav1.Userset{
			Userset: &fgav1.Userset_This{This: &fgav1.DirectUserset{}},
		})
	}
	for _, implied := range r.Implies {
		terms = append(terms, &fgav1.Userset{
			Userset: &fgav1.Userset_ComputedUserset{
				ComputedUserset: &fgav1.ObjectRelation{Relation: implied},
			},
		})
	}
	for _, inh := range r.Inherits {
		terms = append(terms, &fgav1.Userset{
			Userset: &fgav1.Userset_TupleToUserset{
				TupleToUserset: &fgav1.TupleToUserset{
					Tupleset:        &fgav1.ObjectRelation{Relation: inh.Through},
					ComputedUserset: &fgav1.ObjectRelation{Relation: inh.Relation},
				},
			},
		})
	}

	switch len(terms) {
	case 0:
		// Assemble refuses this, so reaching it means the model was built by
		// something other than Assemble.
		return nil, fmt.Errorf("openfga: %s.%s resolves to nothing", typeName, r.Name)
	case 1:
		return terms[0], nil
	default:
		return &fgav1.Userset{
			Userset: &fgav1.Userset_Union{Union: &fgav1.Usersets{Child: terms}},
		}, nil
	}
}
